version: "3.8"
services:
  travelstay-backend:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6
    container_name: travelstay-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mongo
    volumes:
      - ./mongo-data:/data/db