services:
  travelstay-backend:
    build: .
    env_file: .env        # оставляем
    environment:
      - MONGO_URL=mongodb://mongodb:27017/Travel   # пробрасываем наружную во внутреннюю
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: Travel
    volumes:
      - ./mongo-data:/data/db